#
# File:         makefile.g95
# Author:       Julian Smart
# Created:      1999
# Updated:
# Copyright:    (c) Julian Smart, 1999
#
# Makefile for wxWindows sample (Cygwin/Mingw32).

WXDIR = $(WXWIN)

TARGET=panoviewer
UTILS = utils.o
OBJECTS = panoviewerapp.o panoviewextractor.o panoviewer.o panolib.o printerror.o mainframe.o client.o $(UTILS)

include $(WXDIR)\src\makeprog.g95

