=head1 NAME

checkpto - Helper program for Hugin's Makefile assistant

=head1 SYNOPSIS

B<checkpto> I<input.pto>

=head1 DESCRIPTION

B<checkpto> examines the connections between images in a project and
reports back the number of parts or image groups in that project


B<checkpto> is used by the Assistant Makefile when creating a new project.

=head1 FURTHER SWITCHES

=over

=item B<--print-output-info>

Print more information about the output

=item B<-generate-argfile=file>

Generate Exiftool argfile

=item B<-no-gpano>

Don't include GPano tags in argfile

=back

=head1 AUTHORS

Thomas Modes

