

=head1 NAME

fulla - Correct lens distortion, vignetting and chromatic aberration

=head1 SYNOPSIS

B<fulla> [options] I<inputfile(s)>


=head1 DESCRIPTION

Apply radial or flat-field vignetting correction as well as geometrical radial
distortion and transversal chromatic aberration correction.

fulla can be used to batch correct a large number of files. Radial distortion coefficients can be read from a lens database.

Vignetting correction is done the same way as described in the nona script file documentation, or from lens database.
Vignetting correction can be done based on a flat-field or a radial scaling.

Vignetting correction by flat-field division:
                        I = I / c,    c = flat-field / mean(flat-field)

Radial vignetting correction:
                        I = I / c,    c = a + b*r^2 + c*r^4 + d*r^6


The radial distortion correction is identical to the one implemented by PanoTools:

r_new = a*r^4 + b*r^3 + c*r^2 + d*r   [1]

Since transversal chromatic aberrations (TCA) leads to differently scaled objects in the
red, green and blue channel, it can be corrected by scaling the red and blue channel
so that they match the green channel. Most applications, like Photoshop or Picture Window Pro
offer TCA correction by linear scaling. This is equal to varying the d parameter in equation [1].

See http://hugin.sf.net/tutorials/tca for a method to determine these parameters.


=head1 OPTIONS

=over

=item B<--green=db|a:b:c:d>

Correct radial distortion coefficient for all channels, (a, b, c, d)
Specify 'db' for database lookup or the 4 coefficients a:b:c:d

=item B<--blue=db|a:b:c:d>

Correct radial distortion coefficients for blue channel, (a, b, c, d). This is
applied on top of the B<--green> distortion coefficients, use for TCA corr
Specify 'db' for database lookup or the 4 coefficients a:b:c:d

=item B<--red=db|a:b:c:d>

Correct radial distortion coefficients for red channel, (a, b, c, d). This is
applied on top of the B<--green> distortion coefficients, use for TCA corr
Specify 'db' for database lookup or the 4 coefficients a:b:c:d


=item B<--camera-maker=Maker>

Camera manufacturer, for database query

=item B<--camera-model=Cam>

Camera name, for database query

=item B<--lensname=Lens>

Lens name, for database query

=over

Specify --camera-maker and --camera-model for fixed lens cameras or --lensname for interchangeable lenses.

=back

=item B<--focallength=50>

Specify focal length in mm, for database query

=item B<--aperature=3.5>

Specify aperture for vignetting data database query

=item B<--dont-rescale>

Do not rescale the image to avoid black borders.

=item B<--flatfield=filename>

Vignetting correction by flatfield division
I = I / c, c = flatfield / mean(flatfield)

=item B<--vignetting=db|a:b:c:d>

Correct vignetting (by division)
Specify db for database look up or the the 4 coefficients a:b:c:d
I = I / ( a + b*r^2 + c*r^4 + d*r^6)

=item B<--linear>

Do vignetting correction in linear color space

=item B<--gamma=value>

Gamma of input data. 
Used for gamma correction before and after flatfield correction

=item B<threads=n>

Number of threads that should be used

=item B<-h|--help>

Display help

=item B<--output=name>

Set output filename. If more than one image is given, the name will be used as suffix.
(default suffix: _corr)

=item B<--compression=value>

Compression of the output files.
For jpeg output: 0-100
For tiff output: PACKBITS, DEFLATE, LZW

=item B<--offset=X:Y>

Horizontal and vertical shift

=item B<--verbose>

Verbose

=back


=head1 AUTHORS

Written by Pablo d'Angelo. Also contains contributions from Douglas Wilkins, Ippei Ukai, Ed Halley, Bruno Postle, Gerry Patterson, Brent Townshend and Thomas Modes.

