=for
Copyright 2008 Cyril Brulebois <cyril.brulebois@enst-bretagne.fr>
Licensed under the same terms as the hugin package itself.
=end


=head1 NAME

hugin - Hugin panorama creator

=head1 SYNOPSIS

B<hugin> I<project_file|image files ...>


=head1 DESCRIPTION

Hugin is a GUI tool for panorama creation.

This man page is a stub, complete documentation of the GUI can be found in the online
manual available in the Help menu.  Moreover there are related CLI tools listed below
in the SEE ALSO section.

=head1 OPTIONS

Hugin has no command-line options.

=head1 SEE ALSO

align_image_stack(1)  autooptimiser(1)  calibrate_lens(1)  celeste_standalone(1)
checkpto(1)  cpclean(1)  cpfind(1)  deghosting_mask(1)  fulla(1)  geocpset(1)  hugin_executor(1)
hugin_hdrmerge(1) hugin_lensdb(1) hugin_stitch_project(1)  icpfind(1)  linefind(1)  nona(1)  pano_modify(1)
pano_trafo(1)  PTBatcherGUI(1)  pto_gen(1)  pto_merge(1)  pto_lensstack(1) 
pto_mask(1)  pto_merge(1)  pto_move(1)  pto_template(1)  pto_var(1)  tca_correct(1)
verdandi(1) vig_optimize(1)

=head1 AUTHORS

Written by Pablo d'Angelo. Also contains contributions from Kai-Uwe Behrmann, Douglas Wilkins, Ippei Ukai, Ed Halley, Bruno Postle, Gerry Patterson and Brent Townshend.


This man page was written by Cyril Brulebois
<cyril.brulebois@enst-bretagne.fr> and updated by Terry Duell, and is licensed under the same
terms as the hugin package itself.
