=head1 NAME

lensdb - Tool for lens database maintenance


=head1 USAGE

=over

=item B<lensdb [--recursive] --populate BASEPATH>

Populate database with information from all pto files in given BASEPATH.
With the --recursive switch all subfolders/directories will also be searched.

=item B<lensdb --compress>

Compresses the database by replacing single values with averaged values.

=item B<lensdb --remove-lens=LENS>

Removes given lens from the database.

=item B<lensdb --remove-camera=MAKER|MODEL>

Removes given camera from the database.

=item B<lensdb --export-database=FILENAME>

Export data from database to external file.

=item B<lensdb --import-from-file=FILENAME>

Import data from external file.

=item B<-h>

Shows help.

=back

Thomas Modes

=head1 AUTHORS

