=head1 NAME

pano_modify - Change output parameters of project file

=head1 SYNOPSIS

B<pano_modify> [options] I<input.pto>

=head1 DESCRIPTION

B<pano_modify> modifies a single Hugin .pto project.

=head1 OPTIONS

=over

=item B<-o>, B<--output=file.pto>

Output Hugin PTO file. Default: <filename>_mod.pto

=item B<-p>, B<--projection=NUMBER>

Sets the output projection to NUMBER
    RECTILINEAR = 0,
    PANORAMA (Circular) = 1,
    EQUIRECTANGULAR = 2,
    FISHEYE_FF = 3,
    STEREOGRAPHIC = 4,
    MERCATOR = 5,
    TRANS_MERCATOR = 6,
    SINUSOIDAL = 7,
    LAMBERT_EQUAL_AREA_CONIC = 8,
    LAMBERT_AZIMUTHAL = 9,
    ALBERS_EQUAL_AREA_CONIC = 10,
    MILLER_CYLINDRICAL = 11,
    PANINI = 12,
    ARCHITECTURAL = 13,
    ORTHOGRAPHIC = 14,
    EQUISOLID = 15,
    EQUI_PANINI = 16,
    BIPLANE = 17,
    TRIPLANE = 18,
    PANINI_GENERAL = 19,
    THOBY   = 20,
    HAMMER  = 21

=item B<--fov=AUTO|HFOV|HFOVxVFOV>

Sets field of view.

AUTO: calculates optimal fov

HFOV|HFOVxVFOV: set to given fov

=item B<-s>, B<--straighten>

Straightens the panorama

=item B<-c>, B<--center>

Centers the panorama

=item B<--canvas=AUTO|num%|WIDTHxHEIGHT>

Sets the output canvas size

AUTO: calculate optimal canvas size

num%: scales the optimal size by given percent

WIDTHxHEIGHT: set to given size

=item B<--crop=AUTO|AUTOHDR|left,right,top,bottom>

Sets the crop rectangle

AUTO: autocrop panorama

AUTOHDR: autocrop HDR panorama

left,right,top,bottom: to given size

=item B<--output-exposure=AUTO|num>

Sets the output exposure value to the mean exposure (AUTO) or to given value

=item B<--output-type=str>

Sets the type of output

Valid items are (multiple items to be separated by a comma)

NORMAL|N: normal panorama

STACKSFUSEDBLENDED|BF: LDR panorama with blended stacks

EXPOSURELAYERSFUSED|FB: LDR panorama with fused exposure layers (any arrangement)

HDR: HDR panorama

REMAP: remapped images with corrected exposure

REMAPORIG: remapped images with uncorrected exposure

HDRREMAP: remapped images in linear color space

FUSEDSTACKS: exposure fused stacks

HDRSTACKS: HDR stacks

EXPOSURELAYERS: blended exposure layers

=item B<--ldr-file=JPG|TIF|PNG>

Sets the filetype for LDR panorama output

=item B<--ldr-compression=str>

Sets the compression for LDR panorama output

For TIF: NONE|PACKBITS|LZW|DEFLATE

For JPG: quality as number

=item B<--hdr-file=EXR|TIF>

Sets the filetype for HDR panorama output

=item B<--hdr-compression=str>

Sets the compression for HDR panorama output

For TIF: NONE|PACKBITS|LZW|DEFLATE

=item B<--blender=ENBLEND|INTERNAL>

Sets the blender to be used at stitching stage

=item B<--rotate=yaw,pitch,roll>

Rotates the whole panorama with the given angles

=item B<--translate=x,y,z>

Translates the whole panorama with the given values

=item B<-h>, B<--help>

Shows help

=back

=head1 AUTHORS

Thomas Modes

