=head1 NAME

pano_trafo - Transform image coordinates.

=head1 SYNOPSIS

B<pano_trafo> [options] I<pano.pto> I<image_number>

=head1 DESCRIPTION

B<pano_trafo> reads image coordiates (x y) from standard input and
prints the corresponding panorama coordinates to standard output.

=head1 OPTIONS

=over

=item B<-r> 

Reverse transformation, read panorama coordinates and print image
coordinates.

=item B<-h>

shows help

=back

=head1 AUTHORS

Pablo d'Angelo
