#ifndef __HUGIN_VERSION_H__

#define VERSION_MAJOR ${V_MAJOR}
#define VERSION_MINOR ${V_MINOR}
#define VERSION_PATCH ${V_PATCH}
#define HUGIN_WC_REVISION ${HUGIN_WC_REVISION}

#define PACKAGE_VERSION "${HUGIN_PACKAGE_VERSION}"


#endif
